### ISSUE TITLE
把标签选择器后跟伪类误以为是属性名后跟属性值在冒号后加入了空格

### ISSUE THREAD

**Issue by jingchaofang** [ecomfe/fecs#257]
```less
.class{
    li:last-child {
        color: #fff;
    }
    li:hover {
        color: #fff;
    }
    .class {
        color: #fff;
    }
}
```
格式化后对于嵌套下的伪类的冒号后也会加空格，导致less编译失败

格式化错误可能原因：把标签选择器后跟伪类误以为是属性名后跟属性值在冒号后加入了空格，希望做进一步判断
