### ISSUE TITLE
.fecsrc 中fecs-indent关不掉

### ISSUE THREAD

**Issue by tjpanda88** [ecomfe/fecs#357]
``` yml
eslint:
    globals:
        layui: true
    rules:
        indent: "2"
        fecs-indent: 0
```

我想在.fecsrc文件中把fecs-indent中关掉，可是一直不生效
